#!/bin/bash

default_size=80


# Get username
read -p "[Username]: " user

# Get domain
read -p "[Domain]: " domain

# Get screen size
while true; do
    read -p "[Screen size ($default_size)]: " size

    if [[ $size == '' ]]; then
        size=$default_size
        break
    fi

    if [[ $size != *[!0-9]* ]]; then
        break
    fi
done


# Get IP
while true; do
    read -p "[IP Address]: " ip

    if [[ $ip != '' ]]; then
        break
    fi
done


rdesktop -u "$user" -d "$domain" -p - -g "$size%" "$ip"
